name: CI

on: [ workflow_dispatch, push, pull_request ]

jobs:
  ci_stable:
    runs-on: macos-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          target: aarch64-apple-ios

      - name: Format check
        run: cargo fmt --check

      - name: Clippy check
        run: cargo clippy --no-deps --all-targets --all-features -- -D warnings

      - name: Build and Test Keychain
        run: |
          cargo test --lib --verbose --features keychain
          cargo test --lib --verbose --features keychain -- --ignored

      - name: Build instantiation example
        run: cargo build --verbose --all-features --example instantiation

      - name: Build protected examples
        run: cargo build --target aarch64-apple-ios --verbose --features protected --examples

  ci_msrv:
    runs-on: macos-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install rust MSRV
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85
          components: clippy

      - name: Clippy check
        run: cargo clippy --no-deps --all-targets --all-features -- -D warnings
